### ISSUE TITLE
Feature Request：声色変更

### ISSUE THREAD

**Issue by lightsquall** [noriokun4649/Discord-TTS-Voice-channel-Bot#6]
作者様
いつもお世話になっております。

普段利用させていただいております。

機能要望となります。
Botを利用している際、複数人がチャットしていると、全部同じ声なので
誰が何しゃべっているかわからない状況が発生します。

可能であれば人毎に自動で声色やスピード、モードを変えれるとうれしいです

余力あれば将来的に対応いただけますと幸いです

**Comment by noriokun4649** [comment]
お久しぶりです。

声色につきましては既に 1a132f177e2c355e19096f40d56e4b9104dbc2df より人によって声色が変わるよう変更されています。
ピッチ、スピード、モードに関しては今後余裕があれば対応したいと思います。

**Comment by lightsquall** [comment]
失礼しました！

早速1.0.3をDeployしてみたんですが、以下のエラーになってしまって成功しませんでした。
お手数ですが、ご確認いただけますと幸いです
環境はGCP Debian でDocker version 20.10.7, build f0df350　です

> discord-tts-voice-channel-bot@1.0.1 start /var/docker/discord-tts-bot
> node voice_bot_node.js
/var/docker/discord-tts-bot/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^
Error: Configuration property "UrlReplaceText" is not defined
    at Config.get (/var/docker/discord-tts-bot/node_modules/config/lib/config.js:182:11)
    at readConfig (/var/docker/discord-tts-bot/voice_bot_node.js:45:29)
    at Object.<anonymous> (/var/docker/discord-tts-bot/voice_bot_node.js:112:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-tts-voice-channel-bot@1.0.1 start: `node voice_bot_node.js`
npm ERR! Exit status 1

npm ERR! Failed at the discord-tts-voice-channel-bot@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-16T15_30_39_690Z-debug.log

**Comment by lightsquall** [comment]
失礼しました。イメージ差し替えだと駄目だったんですが、0から作ったらOKでした。
本件は忘れてください。

また、声色変更できました！！

ご対応ありがとうございました！！
